#!/usr/bin/env bash

LAST_PWD=$(pwd)

if [ ! $PKGS_DIR ]; then PKGS_DIR=$HOME/.snpm; fi
if [ ! $NPM_BINS ]; then NPM_BINS=npm; fi
if [ ! -r $PKGS_DIR ]; then mkdir $PKGS_DIR; fi

if [ ! -f $(pwd)/package.json ]; then
	echo "[snpm] Initializing.... "
	$NPM_BINS init -fy > /dev/null
fi

if [ ! -x $(pwd)/node_modules ]; then 
	echo -n "[snpm] Linking.... "
	ln -sr $PKGS_DIR/.packages $(pwd)/node_modules
	if [ $? != 0 ]; then 
		rm $(pwd)/node_modules
		echo "[snpm] Error fixed. Please try again."
		exit 1
	fi
	echo "Linked"
fi

if [ ! -f $PKGS_DIR/package.json ]; then
	echo -n "[snpm] Initializing for first time use.... "
	echo "{}" > $PKGS_DIR/package.json
	echo "Done"
fi

if [ ! -f $PKGS_DIR/remove ]; then
	echo -n "[snpm] Creating Package Remover.... "
	cat > $PKGS_DIR/remove <<- EOM
		#!/usr/bin/env bash
		if [ ! \$PKGS_DIR ]; then PKGS_DIR=\$HOME/.snpm; fi
		if [ ! \$NPM_BINS ]; then NPM_BINS=npm; fi

		if [ ! \$1 ]; then echo "Usage: snpm remove [pkgname]"; exit 1; fi
		cd \$PKGS_DIR
		ln -sr \$PKGS_DIR/.packages \$PKGS_DIR/node_modules
		\$NPM_BINS init -y
		\$NPM_BINS remove $@ --no-save
		rm \$PKGS_DIR/node_modules
	EOM
	chmod +x $PKGS_DIR/remove
	echo "Done"
fi

if [ ! $1 ]; then
	cat <<- EOF

	Usage: snpm [method] [args]

	Methods:
	
	 install - Installing packages
	 remove  - Uninstalling/Removing packages
	
	EOF
	exit 1
fi

if [ $1 == "remove" ]; then
	bash -c "$PKGS_DIR/$@"
	exit 0
fi

if [ ! -x $PKGS_DIR/node_modules ]; then mkdir $PKGS_DIR/node_modules; fi
if [ ! -x $PKGS_DIR/.packages ]; then mkdir $PKGS_DIR/.packages; fi
mv $PKGS_DIR/package.json $PKGS_DIR/package.backup.json
cp $(pwd)/package.json $PKGS_DIR/package.json
cd $PKGS_DIR
echo "[snpm] Executing \"$NPM_BINS $@\"...."
$NPM_BINS $@
mv $PKGS_DIR/package.json $LAST_PWD/package.json
mv $PKGS_DIR/package.backup.json $PKGS_DIR/package.json
echo -n "[snpm] Saving to $PKGS_DIR/.packages.... "
cp -rf $PKGS_DIR/node_modules/* $PKGS_DIR/.packages > /dev/null
rm -rf $PKGS_DIR/node_modules && mkdir $PKGS_DIR/node_modules
echo "Done"
